 swipe:
  4:
    left:
      command: 'xdotool key Super+s'
    right:
      command: 'xdotool key Super+s'
    up:
      command: 'xdotool key Super+Ctrl+j'
    down:
      command: 'xdotool key Super+Ctrl+k'

  3:
    left:
      command: 'xdotool key Alt+Left'
    right:
      command: 'xdotool key Alt+Right'
    down:
      command: 'xdotool key Super+a'
pinch:
  in:
    command: 'xdotool key Ctrl+plus'
    threshold: 0.75
  out:
     command: 'xdotool key ctrl+minus'
     threshold: 0.75

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
